[project]
name = "rabbitmq-email-notifier"
version = "0.0.1"

[tool.pytest.ini_options]
pythonpath = [
  ".", "rabbitmq"
]

[tool.project-paths]
dir_unit_out = "tests/unit/out/"
dir_int_out = "tests/integration/out/"

[tool.setuptools]
packages = ["rabbitmq"]